<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<None Include="Properties\launchSettings.json" />
		<!-- Locales must be embedded as {Namespace.Locale.FILENAME.json} -->
		<EmbeddedResource Include="..\Locale\*.json" Visible="false" LinkBase="Locale" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="ResoniteModLoader" Version="5.0.1" />
		<PackageReference Include="Lib.Harmony" Version="2.4.2" />
	</ItemGroup>
	
	<ItemGroup>
		<Reference Include="FrooxEngine" />
		<Reference Include="Elements.Core" />
	</ItemGroup>
	
	<Target Name="PostBuild" AfterTargets="PostBuildEvent" Condition="'$(CopyToGame)'=='true' And Exists('$(AppPath)')">
		<Copy SourceFiles="$(TargetPath)" DestinationFolder="$(AppPath)$(ModLoaderShort)_mods" />
		<Message Text="Copied $(TargetFileName) to $(AppPath)$(ModLoaderShort)_mods" Importance="high" />
	</Target>
</Project>